project_id: '860498'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /app/src/main/res/values/strings.xml
    ignore:
      - /app/src/main/res/values-v24/
      - /app/src/main/res/values-night/
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
